### ISSUE TITLE
"override" build error

### ISSUE THREAD

**Issue by samvinanzi** [robotology/segmentation#8]
Hello!
I was trying to install this repository but I encountered a build error that I really don't know how to solve:

```
[ 30%] Building CXX object edison/CMakeFiles/EdisonSegmentation.dir/EdisonSegmModule.cpp.o
In file included from /home/samuele/Research/repositories/segmentation/edison/include/SegmentationModule.h:17:0,
                 from /home/samuele/Research/repositories/segmentation/edison/EdisonSegmModule.h:33,
                 from /home/samuele/Research/repositories/segmentation/edison/EdisonSegmModule.cpp:14:
/home/samuele/Research/repositories/segmentation/edison/include/SpeedUpLevelComm.h:29:23: error: ‘virtual std::__cxx11::string SpeedUpLevelCommVocab::toString(int) const’ marked ‘override’, but does not override
   virtual std::string toString(int input) const override;
                       ^
edison/CMakeFiles/EdisonSegmentation.dir/build.make:62: recipe for target 'edison/CMakeFiles/EdisonSegmentation.dir/EdisonSegmModule.cpp.o' failed
make[2]: *** [edison/CMakeFiles/EdisonSegmentation.dir/EdisonSegmModule.cpp.o] Error 1
CMakeFiles/Makefile2:122: recipe for target 'edison/CMakeFiles/EdisonSegmentation.dir/all' failed
make[1]: *** [edison/CMakeFiles/EdisonSegmentation.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Do you have any suggestions on how to proceed? Thank you in advance!

**Comment by pattacini** [comment]
Hi @samvinanzi 

Most of the code of the iCub eco-system has been updated to work with versions of YARP >= `3.0.0`, which brings breaking changes in the API.

Thereby, the suggestion is to update YARP first.

**Comment by samvinanzi** [comment]
I wasn't aware of the major version change, of course that explains everything. Many thanks for the fast reply :)
